/**
 * OAuth 2.0 authentication for the Google Calendar API.
 *
 * Uses the Authorization-Code flow with PKCE (Proof Key for Code Exchange)
 * so there is no client secret embedded in the plugin source.  The user
 * supplies their own Google Cloud Console client ID.
 *
 * Token storage is handled by the plugin's data.json via callbacks.
 */

import { Notice, requestUrl } from 'obsidian';
import type { OAuthTokens, TokenEndpointResponse } from './types';

// ── Constants ────────────────────────────────────────────────────────────────

const AUTH_ENDPOINT = 'https://accounts.google.com/o/oauth2/v2/auth';
const TOKEN_ENDPOINT = 'https://oauth2.googleapis.com/token';

/**
 * The OAuth redirect URI.
 *
 * Option D: this plugin registers a "Web application" OAuth client in
 * Google Cloud Console (not "Desktop app"/native), which requires a real
 * `https://` redirect URI — loopback addresses are not accepted for that
 * client type. The redirect target is a static, backend-free page hosted
 * on GitHub Pages (`docs/oauth-redirect.html` in this repo, served from the
 * `/docs` folder on the default branch). Google delivers the `code` and
 * `state` params via the query string (`window.location.search`) on that
 * page; the user copies the code and pastes it into the plugin's settings
 * pane to complete the exchange. Confirmed viable in the Task 0b spike
 * (see /tmp/crew-handoff/t_1cfed21d/SPIKE_task0b_weblient_redirect.md).
 *
 * The exact URI here must match, character-for-character, an "Authorized
 * redirect URI" entry on the Web-application OAuth client in Google Cloud
 * Console.
 */
export const REDIRECT_URI = 'https://jonmccon.github.io/obsidian-time-blocks/oauth-redirect.html';

/** Scopes required for read + write calendar access. */
export const CALENDAR_SCOPES = 'https://www.googleapis.com/auth/calendar';

/** Read-only scope (for users who only want to pull events). */
export const CALENDAR_SCOPES_READONLY =
	'https://www.googleapis.com/auth/calendar.readonly';

// ── PKCE helpers ─────────────────────────────────────────────────────────────

/** Generates a cryptographically random code verifier (43-128 chars, RFC 7636). */
export function generateCodeVerifier(): string {
	const array = new Uint8Array(32);
	crypto.getRandomValues(array);
	return base64UrlEncode(array);
}

/**
 * Generates a cryptographically random state parameter for CSRF protection.
 * The value is included in the authorization URL and must be validated when
 * the redirect URI is received.
 */
export function generateState(): string {
	const array = new Uint8Array(16);
	crypto.getRandomValues(array);
	return base64UrlEncode(array);
}

/** Derives the S256 code challenge from the code verifier. */
export async function generateCodeChallenge(verifier: string): Promise<string> {
	const data = new TextEncoder().encode(verifier);
	const digest = await crypto.subtle.digest('SHA-256', data);
	return base64UrlEncode(new Uint8Array(digest));
}

/** Base64-URL encodes a byte array (no padding). */
function base64UrlEncode(bytes: Uint8Array): string {
	let binary = '';
	for (const byte of bytes) {
		binary += String.fromCharCode(byte);
	}
	return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// ── Auth flow ────────────────────────────────────────────────────────────────

/** Parameters needed to build the authorization URL. */
export interface AuthUrlParams {
	clientId: string;
	codeChallenge: string;
	scopes: string;
	redirectUri?: string;
	/**
	 * CSRF protection state token.  Generated by `generateState()` and stored
	 * by the caller so it can be verified when the redirect is received.
	 */
	state?: string;
}

/**
 * Builds the Google OAuth 2.0 authorization URL that the user opens in their
 * browser to grant permission.
 */
export function buildAuthUrl(params: AuthUrlParams): string {
	const redirectUri = params.redirectUri ?? REDIRECT_URI;
	const queryParams: Record<string, string> = {
		client_id: params.clientId,
		redirect_uri: redirectUri,
		response_type: 'code',
		scope: params.scopes,
		code_challenge: params.codeChallenge,
		code_challenge_method: 'S256',
		access_type: 'offline',
		prompt: 'consent',
	};
	if (params.state) {
		queryParams.state = params.state;
	}
	const query = new URLSearchParams(queryParams);
	return `${AUTH_ENDPOINT}?${query.toString()}`;
}

/** Parameters needed to exchange an authorization code for tokens. */
export interface TokenExchangeParams {
	clientId: string;
	code: string;
	codeVerifier: string;
	redirectUri?: string;
}

/**
 * Exchanges the authorization code for access + refresh tokens.
 *
 * Uses Obsidian's `requestUrl` so it works on both desktop and mobile.
 */
export async function exchangeCodeForTokens(
	params: TokenExchangeParams
): Promise<OAuthTokens> {
	const redirectUri = params.redirectUri ?? REDIRECT_URI;
	const body = new URLSearchParams({
		client_id: params.clientId,
		code: params.code,
		code_verifier: params.codeVerifier,
		grant_type: 'authorization_code',
		redirect_uri: redirectUri,
	});

	const resp = await requestUrl({
		url: TOKEN_ENDPOINT,
		method: 'POST',
		headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
		body: body.toString(),
	});

	const data = resp.json as TokenEndpointResponse;
	return tokenResponseToOAuthTokens(data);
}

/**
 * Refreshes an expired access token using the stored refresh token.
 *
 * Returns updated tokens.  If the server rotates refresh tokens the new one
 * is included; otherwise the original refresh_token is preserved.
 */
export async function refreshAccessToken(
	clientId: string,
	refreshToken: string
): Promise<OAuthTokens> {
	const body = new URLSearchParams({
		client_id: clientId,
		refresh_token: refreshToken,
		grant_type: 'refresh_token',
	});

	const resp = await requestUrl({
		url: TOKEN_ENDPOINT,
		method: 'POST',
		headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
		body: body.toString(),
	});

	const data = resp.json as TokenEndpointResponse;
	const tokens = tokenResponseToOAuthTokens(data);
	// Preserve the existing refresh token if the server didn't issue a new one.
	if (!tokens.refresh_token) {
		tokens.refresh_token = refreshToken;
	}
	return tokens;
}

/** Returns true when the stored access token has expired (or will within 60 s). */
export function isTokenExpired(tokens: OAuthTokens): boolean {
	return Date.now() >= tokens.expires_at - 60_000;
}

// ── Shared authorization-completion flow ─────────────────────────────────────

/**
 * Context needed by `completeAuthorization` to finish an in-progress PKCE
 * flow, regardless of *how* the code+state pair was obtained (manual paste
 * into the settings pane, or the `obsidian://gcal-callback` protocol
 * handler). Kept intentionally free of any Obsidian `Plugin`/`SettingTab`
 * coupling so the control-flow logic (in particular the CSRF guard) lives in
 * exactly one place and behaves identically from both callers.
 */
export interface CompleteAuthorizationContext {
	/** The OAuth client ID configured by the user. */
	clientId: string;
	/**
	 * The `state` value generated when the authorization URL was built
	 * (stored by the caller when the "Authorize" flow was started). `null`
	 * if no flow is currently in progress.
	 */
	pendingState: string | null;
	/**
	 * The PKCE code verifier generated when the authorization URL was
	 * built. `null` if no flow is currently in progress.
	 */
	pendingCodeVerifier: string | null;
	/**
	 * Called with the freshly obtained tokens once the exchange succeeds.
	 * Typically persists them into plugin settings.
	 */
	onSuccess: (tokens: OAuthTokens) => void | Promise<void>;
	/**
	 * Called after a successful exchange to clear any in-progress-auth
	 * state (pending code verifier / state / auth URL) so a stale flow
	 * cannot be reused.
	 */
	resetPendingAuth: () => void;
	/**
	 * Surfaces a message to the user. Defaults to `new Notice(message)`
	 * when omitted (tests may override this to assert on messages without
	 * depending on the Obsidian Notice UI).
	 */
	notify?: (message: string) => void;
}

/**
 * Completes a Google OAuth 2.0 authorization-code flow: validates the CSRF
 * `state` guard, exchanges the code for tokens, and reports the outcome via
 * `ctx.notify` (defaulting to a `Notice`).
 *
 * This is the single shared implementation used by both the manual
 * code-paste flow (settings pane) and the `obsidian://gcal-callback`
 * protocol-handler fast path — the CSRF guard and error/success messaging
 * must behave identically from either entry point.
 */
export async function completeAuthorization(
	code: string,
	state: string | null,
	ctx: CompleteAuthorizationContext
): Promise<void> {
	const notify = ctx.notify ?? ((message: string) => { new Notice(message); });

	if (!ctx.pendingCodeVerifier) {
		notify('Time blocks: click authorize first.');
		return;
	}

	// Validate state to guard against CSRF.
	if (
		state !== null &&
		(ctx.pendingState === null || state !== ctx.pendingState)
	) {
		notify(
			'Time blocks: authorization state mismatch — possible security issue. Please authorize again.'
		);
		ctx.resetPendingAuth();
		return;
	}

	try {
		const tokens = await exchangeCodeForTokens({
			clientId: ctx.clientId,
			code,
			codeVerifier: ctx.pendingCodeVerifier,
		});
		await ctx.onSuccess(tokens);
		ctx.resetPendingAuth();
		notify('Time blocks: signed in to calendar.');
	} catch (err) {
		notify(`Time blocks: authentication failed: ${String(err)}`);
	}
}

// ── Internal helpers ─────────────────────────────────────────────────────────

function tokenResponseToOAuthTokens(resp: TokenEndpointResponse): OAuthTokens {
	if (resp.error) {
		const detail = resp.error_description
			? `${resp.error} — ${resp.error_description}`
			: resp.error;
		throw new Error(`OAuth token error: ${detail}`);
	}
	return {
		access_token: resp.access_token,
		refresh_token: resp.refresh_token,
		expires_at: Date.now() + resp.expires_in * 1000,
		token_type: resp.token_type,
		scope: resp.scope,
	};
}
